### ISSUE TITLE
Missing License for the Project

### ISSUE THREAD

**Issue by gizmo-ds** [07akioni/seemly#85]
Hi 07akioni,

I noticed that this project does not seem to have an open-source license specified. As I am using `naive-ui`, which depends on this package, I would like to confirm the licensing terms to ensure compliance with open-source requirements.

Without a clear license, it's difficult to determine whether the code can be used, modified, or distributed in other projects. Could you please add a license file to clarify the terms under which this package can be used?

Thank you for your work on this project, and I look forward to your response.

**Comment by gizmo-ds** [comment]
Additionally, while the `package.json` specifies the MIT license, the repository does not include the actual license text. Since the MIT license requires that a copy of the license be provided, the absence of the license file makes it impossible for me to fully comply with its terms.

**Comment by 07akioni** [comment]
fixed
